apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-dev
  namespace: openshift-gitops
spec:
  project: web-app
  source:
    repoURL: https://github.com/sailaja/openshift-gitops-demo.git
    targetRevision: main
    path: apps/web-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: web-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true      # auto-revert manual drift
    syncOptions:
      - CreateNamespace=true
